#!/bin/bash

# GHAS Vulnerability Insights - Organization Vulnerability Overview Demo
# This script demonstrates the new organization-wide vulnerability analysis feature

echo "=== GHAS Vulnerability Insights - New Feature Demo ==="
echo "Organization Vulnerability Overview Component"
echo ""

echo "🎯 Feature Overview:"
echo "✅ Aggregates vulnerabilities across all repositories in an organization"
echo "✅ Categorizes vulnerabilities by scanning type:"
echo "   - SAST (Static Application Security Testing) - Code Scanning"
echo "   - Leaked Secrets - Secret Scanning"
echo "   - SCA (Software Composition Analysis) - Dependabot"
echo "✅ Provides severity breakdown (Critical, High, Medium, Low)"
echo "✅ Visualizes data with interactive charts and graphs"
echo "✅ Real-time data from GitHub REST API"
echo ""

echo "🔧 Technical Implementation:"
echo "Backend Changes:"
echo "  📁 New DTOs:"
echo "    - OrganizationVulnerabilityStatsDto.java"
echo "    - DependabotAlertDto.java"
echo "    - SecretScanningAlertDto.java"
echo ""
echo "  🔧 Enhanced Services:"
echo "    - VulnerabilityAnalysisService.java (comprehensive analysis)"
echo "    - GitHubApiService.java (new API endpoints)"
echo ""
echo "  🌐 New API Endpoint:"
echo "    - GET /api/github/organizations/{orgName}/vulnerability-stats"
echo ""

echo "Frontend Changes:"
echo "  📊 New Component:"
echo "    - OrganizationVulnerabilityOverview.tsx"
echo ""
echo "  📈 Features:"
echo "    - Summary cards with total counts"
echo "    - Pie chart showing distribution by scanning type"
echo "    - Stacked bar chart showing severity breakdown"
echo "    - Color-coded severity indicators"
echo "    - Responsive Material-UI design"
echo ""

echo "🚀 Integration:"
echo "  - Added to Analytics dashboard"
echo "  - Included in PDF export functionality"
echo "  - Uses existing authentication system"
echo "  - Follows established error handling patterns"
echo ""

echo "📊 Data Sources:"
echo "  - GitHub Code Scanning Alerts API"
echo "  - GitHub Dependabot Alerts API"
echo "  - GitHub Secret Scanning Alerts API"
echo ""

echo "🎨 UI Elements:"
echo "  - SAST vulnerabilities: Red color scheme"
echo "  - Leaked Secrets: Teal color scheme"
echo "  - SCA vulnerabilities: Blue color scheme"
echo "  - Severity colors: Critical (Dark Red), High (Red), Medium (Orange), Low (Green)"
echo ""

echo "✨ Benefits:"
echo "  - Organization-wide security visibility"
echo "  - Executive-level reporting capabilities"
echo "  - Actionable insights for security teams"
echo "  - Compliance and audit support"
echo ""

echo "🔄 To see this feature in action:"
echo "1. Start the backend: cd backend && mvn spring-boot:run"
echo "2. Start the frontend: cd frontend && npm start"
echo "3. Navigate to the Analytics page"
echo "4. View the new 'Organization Vulnerability Overview' section"
echo ""

echo "=== Demo Complete ==="
